install: gradle wrapper --gradle-version 4.2
language: java
jdk:
  - oraclejdk11
os:
  - linux

branches:
  only:
    - master

script:
  - chmod +x gradle/wrapper/gradle-wrapper.jar
  - ./gradlew check
  - ./gradlew test
  - ./gradlew run
