language: java
before_install:
 - chmod +x ./gradlew
jdk:
  - oraclejdk11
os:
  - linux

branches:
  only:
    - master

script:
    - ls -l 
#   - chmod +x ./gradlew
#   - chmod +x gradlew
#   - chmod +x gradle/wrapper/gradle-wrapper.jar
  - ./gradlew check
  - ./gradlew test
  - ./gradlew run
